# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'https://github.com/mehdi-mtir/demo-forum-iset'
    Contents: '**'
    TargetFolder: 'https://demoforumiset.blob.core.windows.net/demo?sp=racw&st=2025-04-24T04:39:49Z&se=2025-04-24T12:39:49Z&spr=https&sv=2024-11-04&sr=c&sig=7fLw2N0VIQh31jWQIRc%2FnKVvOvc5XXSmCe80ZDj%2FVyQ%3D'
    CleanTargetFolder: false
